services:
  - type: web
    name: ssbprep-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
  - type: web
    name: ssbprep-frontend
    env: static
    buildCommand: cd frontend/my-app-vite && npm install && npm run build
    staticPublishPath: frontend/my-app-vite/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
