export const ALL_USER_REQUEST = 'ALL_USER_REQUEST'
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS'
export const ALL_USER_FAIL = 'ALL_USER_FAIL'

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const ADD_PRODUCT_REQUEST='ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL='ADD_PRODUCT_FAIL'

export const UPDATE_PRODUCT_REQUEST='UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL='UPDATE_PRODUCT_FAIL'
export const UPDATE_PRODUCT_RESET='UPDATE_PRODUCT_RESET'

export const UPDATE_TEST_REQUEST='UPDATE_TEST_REQUEST'
export const UPDATE_TEST_SUCCESS='UPDATE_TEST_SUCCESS'
export const UPDATE_TEST_FAIL='UPDATE_TEST_FAIL'

export const DELETE_TEST_REQUEST='DELETE_TEST_REQUEST'
export const DELETE_TEST_SUCCESS='DELETE_TEST_SUCCESS'
export const DELETE_TEST_FAIL='DELETE_TEST_FAIL'

export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL='DELETE_PRODUCT_FAIL'