export const ALL_PRODUCTS_REQUEST='ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS='ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL='ALL_PRODUCTS_FAIL'

export const TEST_REQUEST='TEST_REQUEST'
export const TEST_SUCCESS='TEST_SUCCESS'
export const TEST_FAIL='TEST_FAIL'

export const TEST_SUBMIT_REQUEST='TEST_SUBMIT_REQUEST'
export const TEST_SUBMIT_SUCCESS='TEST_SUBMIT_SUCCESS'
export const TEST_SUBMIT_FAIL='TEST_SUBMIT_FAIL'

export const TEST_RESULT_REQUEST='TEST_RESULT_REQUEST'
export const TEST_RESULT_SUCCESS='TEST_RESULT_SUCCESS'
export const TEST_RESULT_FAIL='TEST_RESULT_FAIL'

export const CLEAR_ERRORS='CLEAR_ERRORS'